init project
VAnastasia/app-react-next pull request #1
Opened 2021-06-07 04:43 UTC by VAnastasia

2021-06-11 14:46 UTC, kicumkicum requested changes
Отличные чистые компоненты вышли. Молодец!

2021-06-11 14:46 UTC, kicumkicum commented on src/components/dashboard/dashboard.jsx
> +const drawerWidth = 240;
Я бы предложил оформить это как константу. Потому что она выглядит как константа)

2021-06-11 14:46 UTC, kicumkicum commented on src/layouts/page.jsx
> +  function Copyright() {
В теле компонента нужно держать минимальный набор информации. Все что можно вынести стоит вынести. Это делает его легче для чтения и понимания

2021-06-11 14:46 UTC, kicumkicum commented on src/layouts/page.jsx
> +const Page = ({children}) => {
Некоторые функции объявлены через `function`, а некоторые через стрелки. Лучше когда единообразно. И я бы предложил использовать стрелки, потому что они компактнее и их можно использовать только после объявления в коде.

2021-06-11 14:46 UTC, kicumkicum commented on src/layouts/page.jsx
> +import Box from '@material-ui/core/Box';
Используются разные кавычки. Нужно одни. Можно добавить линтер на это или едиторконфиг или и то, и то

2021-06-11 14:46 UTC, kicumkicum commented on src/layouts/page.jsx
> +import Link from '@material-ui/core/Link';
Предлагаю добавить линтер для сортировки импортов по путям

2021-06-14 12:12 UTC, VAnastasia commented on src/components/dashboard/dashboard.jsx
> +const drawerWidth = 240;
Done

2021-06-14 12:12 UTC, VAnastasia commented on src/layouts/page.jsx
> +  function Copyright() {
Done

2021-06-14 12:13 UTC, VAnastasia commented on src/layouts/page.jsx
> +const Page = ({children}) => {
Done

2021-06-14 12:13 UTC, VAnastasia commented on src/layouts/page.jsx
> +import Box from '@material-ui/core/Box';
Done

2021-06-14 12:13 UTC, VAnastasia commented on src/layouts/page.jsx
> +import Link from '@material-ui/core/Link';
Done

2021-06-15 19:23 UTC, kicumkicum approved these changes

2021-06-15 19:25 UTC, merged