add next
VAnastasia/app-react-next pull request #5
Opened 2021-06-28 08:12 UTC by VAnastasia

2021-06-29 09:58 UTC, kicumkicum requested changes
Крутяг! Взяли и переехали)))

2021-06-29 09:58 UTC, kicumkicum commented on .eslintrc
> +{
А почему ты решила поменять формат файла?

2021-06-29 09:58 UTC, kicumkicum commented on pages/categories.jsx
> +  <Page>
Отступы уехали

2021-06-29 09:58 UTC, kicumkicum commented on src/components/categories/categories.jsx
> +      <Link href='/add-category'><a>Добавить категорию</a></Link>
А чем `href` от `to` отличается?

2021-06-29 09:58 UTC, kicumkicum commented on src/components/dashboard/dashboard.jsx
> +            <Link href='/' >
Расскажи, для чего нужно это изменение?

2021-07-01 04:00 UTC, VAnastasia commented on pages/add-category.jsx
> +import AddCategory from '../src/components/add-category/add-category';
pages должна быть на верхнем уровне

2021-07-01 04:00 UTC, VAnastasia commented on .eslintrc
> +{
удобно скопипастить

2021-07-01 04:02 UTC, VAnastasia commented on src/components/categories/categories.jsx
> +      <Link href='/add-category'><a>Добавить категорию</a></Link>
Link в next не тот же Link. что в react-router, он даже не превращается в ссылку

2021-07-01 04:03 UTC, VAnastasia commented on src/components/dashboard/dashboard.jsx
> +            <Link href='/' >
в next нет NavLink

2021-07-01 04:06 UTC, VAnastasia commented on pages/_app.js
> +      jssStyles.parentElement.removeChild(jssStyles);
стили в material-ui с ssr не дружат

2021-07-04 15:11 UTC, VAnastasia commented on pages/categories.jsx
> +  <Page>
Done

2021-07-04 17:05 UTC, kicumkicum commented on src/components/categories/categories.jsx
> +      <Link href='/add-category'><a>Добавить категорию</a></Link>
Done

2021-07-04 17:05 UTC, kicumkicum commented on src/components/dashboard/dashboard.jsx
> +            <Link href='/' >
Done

2021-07-04 17:05 UTC, kicumkicum commented on pages/_app.js
> +      jssStyles.parentElement.removeChild(jssStyles);
Done

2021-07-04 17:10 UTC, kicumkicum commented on pages/add-category.jsx
> +import AddCategory from '../src/components/add-category/add-category';
Кажется, что их можно поместить и в src. Давай поместим их туда. Чтобы src была точка входа для кода. Это привычная структура для многих проектов и лучше чтобы это поведение не зависело от используемого фреймворка, сборщика и тд. Разработчикам приходится переключаться с проекта на проект и если они имеют схожую структуру, то это происходит менее болезненно

https://nextjs.org/docs/advanced-features/src-directory

2021-07-04 17:11 UTC, kicumkicum commented on .eslintrc
> +{
Done

2021-07-04 17:11 UTC, kicumkicum commented on pages/_app.js
> +      jssStyles.parentElement.removeChild(jssStyles);
Done

2021-07-04 17:21 UTC, kicumkicum requested changes
Тесты лучше было начать делать в отдельной ветке и сделать на них отдельный ПР. Сейчас мы будем обсуждать две задачи и это отсрочит попадание первой задачи в мастер.
Но тесты, несмотря на свою простоту, крутые. Молодец что взялась за них!

2021-07-04 17:21 UTC, kicumkicum commented on package.json
> +    "test": "jest"
Лучше использовать этот скрипт для всех проверок: линтер и тесты. А для тестов завести отдельный, например `test.ui`

2021-07-04 17:21 UTC, kicumkicum commented on src/components/dashboard/dashboard.test.js
> +    expect(screen.getByText(/Дашборд/i)).toBeInTheDocument();
Лучше разделять пустой строкой работу и проверки. Блоки кода читать проще чем полотно

2021-07-04 17:21 UTC, kicumkicum commented on src/components/dashboard/dashboard.test.js
> +    expect(screen.getByText(/Главная/i)).toBeInTheDocument();
Здесь тоже нужны блоки кода

2021-07-07 13:00 UTC, VAnastasia commented on pages/add-category.jsx
> +import AddCategory from '../src/components/add-category/add-category';
Done

2021-07-07 13:01 UTC, VAnastasia commented on package.json
> +    "test": "jest"
Done

2021-07-07 13:01 UTC, VAnastasia commented on src/components/dashboard/dashboard.test.js
> +    expect(screen.getByText(/Дашборд/i)).toBeInTheDocument();
Done

2021-07-07 13:01 UTC, VAnastasia commented on src/components/dashboard/dashboard.test.js
> +    expect(screen.getByText(/Главная/i)).toBeInTheDocument();
Done

2021-07-07 17:25 UTC, kicumkicum approved these changes
Огонь ваще!

2021-07-07 17:25 UTC, merged