tests
VAnastasia/app-react-next pull request #6
Opened 2021-07-12 06:24 UTC by VAnastasia

2021-07-12 14:47 UTC, kicumkicum reviewed
Good job 👍🏽 
- [x] Нужно заголовок ПРа начинать с глагола. Чтобы лучше понимать, что он делает. `Add/Update/Remove/Fix/etc.`

2021-07-12 14:47 UTC, kicumkicum commented on src/components/add-category/add-category.test.js
> +  it('sends form on save', async() => {
Названия кейса не соответствует текущей проверке. Ведь не происходит никакого сохранения. Происходит проверка, что для конкретной кнопки вызывается конкретный обработчик.

Описание тест-кейса не должно вводить в заблуждение

2021-07-12 14:47 UTC, kicumkicum commented on src/components/add-category/add-category.test.js
> +  it('sends form on save', async() => {
Обычно после оператора идет пробел

2021-07-12 14:47 UTC, kicumkicum commented on src/components/add-category/add-category.test.js
> +    fireEvent.change(screen.getByLabelText(/Название/i), { target: { value: 'Название' } });
Тут только так можно замокать evt? Откуда в реальном коде будет заполняться  `value: Название`

2021-07-12 14:47 UTC, kicumkicum commented on src/components/add-transaction/add-transaction.jsx
> +    setSelectedDate(new Date())
Точка с запятой упущены. Почему не срабатывает линтер на это?)

2021-07-12 14:47 UTC, kicumkicum commented on src/components/add-transaction/add-transaction.test.js
> +    fireEvent.change(screen.getByLabelText(/Сумма/i), { target: { value: '1000' } });
А, кажется понял. Это как будто пользователь ввел в инпут 1000?

2021-07-12 14:48 UTC, kicumkicum requested changes
Не верно указал статус ревью выше

2021-07-14 05:18 UTC, VAnastasia commented on src/components/add-transaction/add-transaction.test.js
> +    fireEvent.change(screen.getByLabelText(/Сумма/i), { target: { value: '1000' } });
да, нашли инпут и ввели значение 1000

2021-07-14 05:23 UTC, VAnastasia commented on src/components/add-category/add-category.test.js
> +  it('sends form on save', async() => {
Done

2021-07-14 05:24 UTC, VAnastasia commented on src/components/add-category/add-category.test.js
> +  it('sends form on save', async() => {
Done

2021-07-14 05:24 UTC, VAnastasia commented on src/components/add-transaction/add-transaction.jsx
> +    setSelectedDate(new Date())
Done

2021-07-19 15:23 UTC, kicumkicum commented
![Screenshot_2021-07-19-19-21-07-003_com android chrome](https://user-images.githubusercontent.com/5058981/126184814-99657a73-9af0-4df8-a6ad-1408fbfda094.jpg)
Настя, перезапрашивай вот тут ревью. Так мне проще будет понимать, что ты сделала всё, что хотела и мне можно смотреть)

2021-07-19 15:29 UTC, merged