Feature/ts
VAnastasia/app-react-next pull request #7
Opened 2021-07-19 08:44 UTC by VAnastasia

2021-07-21 05:38 UTC, kicumkicum requested changes
Отличный переезд! Но ПР получился большим. Я ещё не досмотрел про Стор. Про него позже напишу. Пока можно вносить эти правки

2021-07-25 05:48 UTC, VAnastasia commented on .babelrc
> +  "plugins": [["@babel/plugin-proposal-decorators", { "legacy": true }]]
Для поддержки декораторов в mobx

2021-07-25 05:48 UTC, VAnastasia commented on next-env.d.ts
> +/// <reference types="next" />
этот файл создает next когда в корне есть tsconfig.json

2021-07-25 05:58 UTC, VAnastasia commented on package.json
> +    "server": "json-server --watch db.json --port 8080"
Кажется, надо ставить доп. зависимости для параллельного запуска

2021-07-25 05:59 UTC, VAnastasia commented on src/store/categories.ts
> +  @observable categories = []
Делает поле "наблюдаемым"

2021-07-25 06:00 UTC, VAnastasia commented on src/store/categories.ts
> +  @action
Обозначает метод, который изменяет observable поле

2021-07-25 06:33 UTC, VAnastasia commented on axios.d.ts
> +export interface AxiosTransformer {
Done

2021-07-25 06:33 UTC, VAnastasia commented on src/components/add-category/add-category.test.tsx
> +
Done

2021-07-26 09:52 UTC, kicumkicum commented on next-env.d.ts
> +/// <reference types="next" />
done

2021-07-26 09:52 UTC, kicumkicum commented on .babelrc
> +  "plugins": [["@babel/plugin-proposal-decorators", { "legacy": true }]]
done

2021-07-26 10:18 UTC, kicumkicum approved these changes
Все отлично. Есть ветки обсуждений, но они опциональны и не блокируют код. Я смержу МР, а в обсуждении мы решим, что делать дальше.

2021-07-26 10:18 UTC, kicumkicum commented on tsconfig.json
> +    "skipLibCheck": true,
Это чтобы тайпинги не устанавливать?

2021-07-26 10:18 UTC, kicumkicum commented on src/store/transactions.ts
> +      })
```suggestion
      });
```

Нужен линтер

2021-07-26 10:18 UTC, kicumkicum commented on src/service/api.ts
> +      console.log(error)
Я бы тут ошибку не проглатывал. Модуль API не знает, кто и как мог бы обработать ошибку и что нужно показать пользователю в этот момент. Залогировать ошибку можно, но лучше ее просто бросить выше. 

В текущем варианте тебе все равно придется неявно это делать, потому что метод вернет `Category[] | undefined`. Только об этом можно забыть и получить непонятный ексепшен в рантайме.

2021-07-26 10:18 UTC, kicumkicum commented on src/service/api.ts
> +      console.log(error)
Вообще методы имеют очень похожий код. Его можно вынести в декораторы или вариант попроще с функцией или приватным методом. Чтобы было что-то вроде

```js
async fetchCategories() {
  return checkErr(() => this._api.get('/categories'));
}

async createCategory(form: Category) {
  return checkErr(checkCreated(() => this._api.post('/categories', form)));
}
```


```js
@checkErr
async fetchCategories() {
  return this._api.get('/categories');
}

@checkErr
@checkCreated
async createCategory(form: Category) {
  return this._api.post('/categories', form);
}
```


Но это FYI. С ходу такую систему придумать не просто. Да и у нее есть свои минусы в процессе отладки. Можно оставить как есть

2021-07-26 10:18 UTC, kicumkicum commented on src/service/api.ts
> +      console.log(error)
Можно это перенести в ишью просто

2021-07-26 10:18 UTC, kicumkicum commented on src/store/categories.ts
> +  @observable categories = []
А что это значит?

2021-07-26 10:18 UTC, merged